[package]
name = "native"
version = "0.1.0"
authors = []
edition = "2021"

[lib]
name = "native"
path = "src/lib.rs"
crate-type = ["cdylib"]

[dependencies]
csv = "1.3.0"
rstar = "0.11.0"
rustler = "0.30.0"
serde = { version = "1.0.188", features = ["derive"] }
